CN-1.2.2 updates
Nero-Hu/Whiteboard-iOS-doc pull request #3
Opened 2023-04-19 02:48 UTC by Nero-Hu

2023-04-23 07:28 UTC, dengyaxi requested changes

2023-04-23 07:28 UTC, dengyaxi commented on Fastboard/CN-API Reference.md
> +- `userPayload`：用户光标显示的用户信息，包括用户的昵称和头像。详见  <a href="#fastuserpayload">`FastUserPayload`</a >。
看上去是可选的，是否说明一下

2023-04-23 07:28 UTC, dengyaxi commented on Fastboard/CN-Release Notes.md
> +- 系统版本低于 iOS 14 的设备上设置 `drawOnlyApplePencil` 可能会造成崩溃。
API文档没搜到drawOnlyApplePencil

2023-04-24 02:47 UTC, vince-hz commented on Fastboard/CN-Release Notes.md
> +- 系统版本低于 iOS 14 的设备上设置 `drawOnlyApplePencil` 可能会造成崩溃。
Fastboard 直接依赖了 Whiteboard.
https://github.com/netless-io/Whiteboard-iOS/blob/master/CHANGELOG.md#21643---2022-10-10

2023-04-24 06:50 UTC, Nero-Hu commented on Fastboard/CN-API Reference.md
> +- `userPayload`：用户光标显示的用户信息，包括用户的昵称和头像。详见  <a href="#fastuserpayload">`FastUserPayload`</a >。
在代码签名里能直接看出来，所以不额外标注

2023-07-04 03:34 UTC, merged