Release 2.16.61
Nero-Hu/Whiteboard-iOS-doc pull request #4
Opened 2023-08-24 03:44 UTC by Nero-Hu

2023-08-24 03:50 UTC, vince-hz approved these changes

2023-08-30 03:09 UTC, vince-hz approved these changes

2023-08-30 06:38 UTC, HeatherWYL commented on iOS-CN/headers/Object/WhiteWindowParams.h
> +/** auto只有在iOS13以上才会生效*/
这条会生成文档么？如果会的话，建议改为：
`WhitePrefersColorSchemeAuto` 仅适用于 iOS 13 及以上的设备。

2023-08-30 06:41 UTC, HeatherWYL commented on iOS-CN/headers/Object/WhiteWindowParams.h
> +@interface WhiteWindowParams : WhiteObject
interface 也要加注释，不然就没有类的描述了

2023-08-30 06:43 UTC, HeatherWYL commented on iOS-CN/headers/Object/WhiteWindowParams.h
> +/** 是否使用窗口最大化，开启后添加的窗口将全屏展示。 默认 NO */
是否使用->是否开启
默认 NO->默认值为 `NO`。

2023-08-30 06:54 UTC, HeatherWYL commented on iOS-CN/release-notes-wb.ios.mdx
> +<VersionSection version="2.16.62 版">
pr名为 2.16.61，这里版本号是 62，确认下是否正确哈

2023-08-30 06:54 UTC, HeatherWYL commented on iOS-CN/release-notes-wb.ios.mdx
> +该版本废弃了白板数据中心（`region`）原有的英国伦敦数据中心（`gb-lon`），并新增了欧洲法兰克福数据中心（`eu`），服务区覆盖欧洲。如果需要使用该数据中心，请在升级到该版本后更新代码，并在控制台-互动白板服务配置中启用该数据中心。
[release-2.16.61](https://github.com/Nero-Hu/Whiteboard-iOS-doc/tree/release-2.16.61)

2023-08-30 07:17 UTC, HeatherWYL commented on iOS-CN/release-notes-wb.ios.mdx
> +新增 `getSlideVolumeWithCompletionHandler` 和 `updateSlideVolume` 方法用于获取和更新 PPT 内音频的音量。
大部分发版说明会写【该版本】新增/修复/改进，可以考虑下是否批量增加

2023-08-30 07:30 UTC, HeatherWYL commented on iOS-CN/headers/SDK/WhiteSDK.h
> + 获取当前 slide 的音量。
获取当前 PPT 幻灯片的音量？

2023-08-30 07:31 UTC, HeatherWYL commented on iOS-CN/headers/SDK/WhiteSDK.h
> + 获取当前 slide 的音量。
或者【获取当前幻灯片】的音量

2023-08-30 07:33 UTC, HeatherWYL commented on iOS-CN/headers/SDK/WhiteSDK.h
> + 获取当前 slide 的音量。
有调用时序限制么？
比如是否需要在共享幻灯片之前调用这个方法获取音量，之类的

2023-08-30 07:34 UTC, HeatherWYL commented on iOS-CN/headers/SDK/WhiteSDK.h
> + 更新当前 slide 的音量。
更新当前 PPT 幻灯片的音量。

2023-08-30 07:36 UTC, HeatherWYL commented on iOS-CN/headers/SDK/WhiteSDK.h
> + 更新当前 slide 的音量。
get 和 update 之间有关系吗？比如是不是不用调 get，也可以随时调用 update？

2023-08-30 07:39 UTC, HeatherWYL commented on iOS-CN/headers/SDK/WhiteSDK.h
> + 设置 多窗口 Slide 回调事件。
多窗口 Slide 是什么意思？

2023-08-30 07:39 UTC, HeatherWYL commented on iOS-CN/headers/SDK/WhiteSDK.h
> + 设置 多窗口 Slide 回调事件。
如果没有特别原因的话，slide 改成 PPT 幻灯片是不是更好些？

2023-08-30 07:49 UTC, HeatherWYL commented on iOS-CN/headers/SDK/WhiteSlideDelegate.h
> + @param completionHandler 替换后的地址回调，完成 url 替换后请调用该方法。
completionHandler 参数描述说【完成 url 替换后请调用该方法】是什么意思？这不是个回调么

2023-08-30 07:49 UTC, HeatherWYL commented on iOS-CN/headers/SDK/WhiteSdkConfiguration.h
> +/** SlideApp 参数。详见 [WhiteSlideAppParams](WhiteSlideAppParams)  */
句尾少了句号

2023-08-30 07:55 UTC, HeatherWYL commented on iOS-CN/headers/SDK/WhiteSdkConfiguration.h
> + 开启之后，需要同时设置 `WhiteSDK.setSlideDelegate` 在 `slideUrlInterrupter` 回调中对 url 进行处理。
开启之后，你需要通过 `WhiteSDK.setSlideDelegate` 设置多窗口 PPT 回调事件，并在 `slideUrlInterrupter` 回调中添加 url 的替换处理逻辑。

2023-08-30 07:56 UTC, HeatherWYL commented on iOS-CN/headers/SDK/WhiteSdkConfiguration.h
> +/** SlideApp 参数。详见 [WhiteSlideAppParams](WhiteSlideAppParams)  */
SlideApp 是个专有名词么？

2023-08-30 07:58 UTC, HeatherWYL commented on iOS-CN/headers/SDK/WhiteSlideDelegate.h
> +typedef void (^SlideUrlInterrupterCallback)(NSString * _Nullable result);
缺少注释

2023-08-30 07:59 UTC, HeatherWYL commented on iOS-CN/headers/SDK/WhiteSlideDelegate.h
> + @param completionHandler 替换后的地址回调，完成 url 替换后请调用该方法。
是不是想说【完成 url 替换后，你需要在该参数中实现拦截逻辑】之类的？

2023-08-30 08:04 UTC, HeatherWYL commented on iOS-CN/release-notes-wb.ios.mdx
> +`WhiteSdkConfiguration` 新增 `enableSlideInterrupterAPI` 配置项。开启后，通过调用 `WhiteSDK.setSlideDelegate` 设置回调对象实现 PPT URL 的拦截替换功能。
1. 建议【配置项。】改为【属性用于开启 Slide 资源 url 拦截替换功能。】
2. 通过调用 `WhiteSDK.setSlideDelegate` 设置回调对象【并在 `slideUrlInterrupter` 回调中添加 PPT URL 的替换处理逻辑，】实现 PPT URL 的拦截替换功能。

2023-08-30 08:05 UTC, HeatherWYL commented on iOS-CN/headers/SDK/WhiteSlideAppParams.h
> +@interface WhiteSlideAppParams : WhiteObject
缺少注释

2023-08-30 08:07 UTC, HeatherWYL commented on iOS-CN/release-notes-wb.ios.mdx
> +`WhiteSdkConfiguration` 新增 `whiteSlideAppParams` 配置项用于 [@netless/app-slide](https://github.com/netless-io/netless-app/tree/master/packages/app-slide) 渲染相关的显示配置。当前支持配置 `WhiteSlideAppParams.showRenderE
第二句【支持配置 xxx，用于配置 xxx】有点冗余，可以直接写：
你可以通过 `WhiteSlideAppParams.showRenderError` 配置显示/隐藏渲染错误提示。

2023-08-30 08:10 UTC, HeatherWYL commented on iOS-CN/headers/SDK/WhiteSdkConfiguration.h
> + * 配置白板的 API 服务器域名列表，可以用于服务器代理。配置后，白板不再使用 sdk 自带配置。
SDK 全大写

2023-08-30 08:11 UTC, HeatherWYL commented on iOS-CN/release-notes-wb.ios.mdx
> +`WhiteSdkConfiguration` 新增 `apiHosts` 配置项, 用于配置白板的 API 服务器域名列表，可用于实现服务器代理。
用于 xxx，可用于 xxx 有些冗余，建议：
用于配置白板的 API 服务器域名列表，例如添加代理服务器域名。

2023-08-30 08:13 UTC, HeatherWYL commented on iOS-CN/headers/SDK/WhiteSdkConfiguration.h
> + * 配置白板的 API 服务器域名列表，可以用于服务器代理。配置后，白板不再使用 sdk 自带配置。
疑问：这是个数组，表示可以配置多个域名。那如果配了自定义代理服务器的域名+声网服务器的域名，那白板也不会使用 SDK 的配置么？（主要是对 SDK 自带配置不太理解

2023-08-30 08:14 UTC, HeatherWYL commented on iOS-CN/headers/Replayer/WhitePlayerConfig.h
> + * 白板请求 modules 数据的地址。配置后不会请求白板默认地址。
那白板默认地址是啥？建议写下

2023-08-30 08:14 UTC, HeatherWYL commented on iOS-CN/headers/Room/WhiteRoomConfig.h
> + * 白板请求 modules 数据的地址。配置后不会请求白板默认地址。
那白板默认地址是啥？建议写下

2023-08-30 08:16 UTC, HeatherWYL commented on iOS-CN/headers/Room/WhiteRoom.h
> +@interface WhiteRoom(MainView)
缺少注释

2023-08-30 08:17 UTC, HeatherWYL commented on iOS-CN/headers/Room/WhiteRoom.h
> + * @warning 该方法只有在文档视图加载完毕时才能调用。不支持多次连续调用，只有当当前的转场动画完毕之后才能进行下一次调用。
只有在当前 xxx
避免两个重复的当

2023-08-30 08:18 UTC, HeatherWYL commented on iOS-CN/headers/Room/WhiteWindowDocsEventOptions.h
> +/// 上一页
这种注释格式也会生成文档吗？

2023-08-30 08:18 UTC, HeatherWYL commented on iOS-CN/headers/Room/WhiteWindowDocsEventOptions.h
> +/// 跳转到某一页 ( 需要配合 `WhiteWindowDocsEventOptions` 使用 )
括号和中文间的空格需删除

2023-08-30 08:19 UTC, HeatherWYL commented on iOS-CN/headers/Room/WhiteWindowDocsEventOptions.h
> +@interface WhiteWindowDocsEventOptions : WhiteObject
缺少注释

2023-08-30 08:19 UTC, HeatherWYL commented on iOS-CN/headers/Room/WhiteRoom.h
> + * @param docsEvent 事件类型。详见 [WhiteWindowDocsEventKey](WhiteWindowDocsEventKey)
句尾缺句号

2023-08-30 08:21 UTC, HeatherWYL commented on iOS-CN/headers/Room/WhiteRoom.h
> + * @param options 可选事件参数。当 `docsEvent` 传入 `WhiteWindowDocsEventJumpToPage` 时，`options` 用于传入跳转的页码。详见 [WhiteWindowDocsEventOptions](WhiteWindowDocsEventOptions)
1. 句尾缺句号。
2. 第二句建议改成：该参数仅在设置 `docsEvent` 为 `WhiteWindowDocsEventJumpToPage` 时有效，用于传入跳转的页码。

2023-08-30 08:23 UTC, HeatherWYL commented on iOS-CN/release-notes-wb.ios.mdx
> +`WhiteWindowParams`新增 `fullscreen`, 用于控制窗口是否全屏。
新增前要加空格

2023-08-30 08:23 UTC, HeatherWYL commented on iOS-CN/release-notes-wb.ios.mdx
> +`WhiteWindowParams`新增 `fullscreen`, 用于控制窗口是否全屏。
用于控制窗口是否全屏显示。
加个显示

2023-08-30 08:24 UTC, HeatherWYL commented on iOS-CN/release-notes-wb.ios.mdx
> +  - `WhiteWindowDocsEventOptions`
这里还有个 WhiteWindowDocsEventKey 吧？

2023-08-30 08:25 UTC, HeatherWYL commented on iOS-CN/headers/Object/WhiteConsts.h
> +extern WhiteRegionKey const WhiteRegionGB DEPRECATED_MSG_ATTRIBUTE("Using WhiteRegionEU instead.");
这个废弃没有在发版说明的 API 变更中写

2023-08-30 08:25 UTC, HeatherWYL commented on iOS-CN/headers/Object/WhiteWindowParams.h
> +/** auto只有在iOS13以上才会生效*/
这下面的枚举都没有注释

2023-08-30 08:25 UTC, HeatherWYL commented on iOS-CN/release-notes-wb.ios.mdx
> +- `WhiteWindowParams`新增 `fullscreen`
新增前要空格

2023-08-30 08:26 UTC, HeatherWYL commented on iOS-CN/headers/SDK/WhiteSdkConfiguration.h
> +@property (nonatomic, strong) WhitePptParams *pptParams __deprecated_msg("use WhiteSlideAppParams instead");
这个废弃没有在发版说明中体现

2023-08-30 08:28 UTC, HeatherWYL commented on iOS-CN/release-notes-wb.ios.mdx
> +- `setSlideDelegate`
建议加上：
- `WhiteSlideDelegate`
  - `slideUrlInterrupter`

2023-08-31 03:26 UTC, Nero-Hu commented on iOS-CN/headers/Object/WhiteWindowParams.h
> +/** auto只有在iOS13以上才会生效*/
ios 我测不了，所以不太确定会不会生成。。。后面试试

2023-08-31 03:34 UTC, Nero-Hu commented on iOS-CN/release-notes-wb.ios.mdx
> +<VersionSection version="2.16.62 版">
临时新增了 62 的改动 所以也改了

2023-08-31 07:06 UTC, Nero-Hu commented on iOS-CN/headers/SDK/WhiteSdkConfiguration.h
> + * 配置白板的 API 服务器域名列表，可以用于服务器代理。配置后，白板不再使用 sdk 自带配置。
@vince-hz

2023-08-31 07:07 UTC, Nero-Hu commented on iOS-CN/headers/Replayer/WhitePlayerConfig.h
> + * 白板请求 modules 数据的地址。配置后不会请求白板默认地址。
@vince-hz

2023-08-31 07:07 UTC, Nero-Hu commented on iOS-CN/headers/Room/WhiteRoomConfig.h
> + * 白板请求 modules 数据的地址。配置后不会请求白板默认地址。
@vince-hz

2023-08-31 07:13 UTC, Nero-Hu commented on iOS-CN/headers/Room/WhiteRoom.h
> +@interface WhiteRoom(MainView)
这里貌似加了也不会体现在文档，我看前面几个都打了 #pragma mark 也不在文档里

2023-08-31 07:15 UTC, Nero-Hu commented on iOS-CN/headers/Room/WhiteWindowDocsEventOptions.h
> +/// 上一页
不会，已修改

2023-08-31 07:42 UTC, vince-hz commented on iOS-CN/headers/SDK/WhiteSdkConfiguration.h
> + * 配置白板的 API 服务器域名列表，可以用于服务器代理。配置后，白板不再使用 sdk 自带配置。
这不是一个通用的代理服务。所以用户在使用这个配置的时候，他需要明确的知道自己的行为。(他需要在自己的服务器里自行完成特定代理行为)。

只要这里填了值，那么 sdk 就会使用这个地址来通信，并不区分是什么服务器。

2023-08-31 07:49 UTC, vince-hz commented on iOS-CN/headers/Replayer/WhitePlayerConfig.h
> + * 白板请求 modules 数据的地址。配置后不会请求白板默认地址。
是指加载一些动态资源的地址，默认配置是通过请求获取的。
https://api.netless.link/v5/configs/regions，不同的区域地址也不一样。
提供了之后也可能会变，所以没什么意义。

这个值是给少量的用户用的，不通过联系我们自己修改没有什么意义

2023-08-31 07:50 UTC, vince-hz commented on iOS-CN/headers/Room/WhiteRoomConfig.h
> + * 白板请求 modules 数据的地址。配置后不会请求白板默认地址。
是指加载一些动态资源的地址，默认配置是通过请求获取的。
[https://api.netless.link/v5/configs/regions，不同的区域地址也不一样。](https://api.netless.link/v5/configs/regions%EF%BC%8C%E4%B8%8D%E5%90%8C%E7%9A%84%E5%8C%BA%E5%9F%9F%E5%9C%B0%E5%9D%80%E4%B9%9F%E4%B8%8D%E4%B8%80%E6%A0%B7%E3%80%82)
提供了之后也可能会变，所以没什么意义。

这个值是给少量的用户用的，不通过联系我们自己修改没有什么意义

2023-08-31 07:50 UTC, Nero-Hu commented on iOS-CN/headers/Replayer/WhitePlayerConfig.h
> + * 白板请求 modules 数据的地址。配置后不会请求白板默认地址。
1

2023-08-31 07:50 UTC, Nero-Hu commented on iOS-CN/headers/SDK/WhiteSdkConfiguration.h
> + * 配置白板的 API 服务器域名列表，可以用于服务器代理。配置后，白板不再使用 sdk 自带配置。
1

2023-09-11 12:25 UTC, atovpeko requested changes

2023-09-11 12:25 UTC, atovpeko commented on iOS-EN（裁剪版）/headers/Room/WhiteRoom.h
> + * @param docsEvent Type of the doc event.See [WhiteWindowDocsEventKey](WhiteWindowDocsEventKey).
Space before "See"

2023-09-11 12:25 UTC, atovpeko commented on iOS-EN（裁剪版）/headers/Room/WhiteWindowDocsEventOptions.h
> + * Jumpt to page.
Jump

2023-09-11 12:25 UTC, atovpeko commented on iOS-EN（裁剪版）/headers/SDK/WhiteSDK.h
> + Gets the volume the PPT slide.
volume OF the PPT slide?

2023-09-11 12:25 UTC, atovpeko commented on iOS-EN（裁剪版）/headers/SDK/WhiteSDK.h
> +                          - A successful call: `volume` ranges from (0,1], indicating the volume the PPT; `error` returns `nil`.
volume OF the PPT

2023-09-11 12:25 UTC, atovpeko commented on iOS-EN（裁剪版）/headers/SDK/WhiteSDK.h
> + The SDK process PPT-related callbacks via [WhiteSlideDelegate](WhiteSlideDelegate).
if "process" is a verb here, it should be "processes"

2023-09-11 12:25 UTC, atovpeko commented on iOS-EN（裁剪版）/headers/SDK/WhiteSlideAppParams.h
> + - `NO`: (Default) Not display rendering errors.
This does not seem correct. Should be either "Do not display" or "Not to display"

2023-10-27 02:40 UTC, merged